apiVersion: apps/v1
kind: Deployment
metadata:
  name: super-admin
  namespace: streamnxt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: super-admin
  template:
    metadata:
      labels:
        app: super-admin
    spec:
      nodeSelector:
        kubernetes.io/hostname: streamnxt-production-worker-api
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: super-admin
          image: ghcr.io/streamnxtplus-oss/ott-super-admin:latest
          ports:
            - containerPort: 3002
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3002"
            - name: API_INTERNAL_URL
              value: "http://api:3001"
          readinessProbe:
            httpGet:
              path: /
              port: 3002
            initialDelaySeconds: 15
            periodSeconds: 5
