apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: streamnxt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      nodeSelector:
        kubernetes.io/hostname: streamnxt-production-worker-frontend
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: web
          image: ghcr.io/streamnxtplus-oss/ott-web:latest
          ports:
            - containerPort: 3003
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3003"
            - name: API_INTERNAL_URL
              value: "http://api:3001"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: streamnxt-secrets
                  key: JWT_SECRET
          readinessProbe:
            httpGet:
              path: /
              port: 3003
            initialDelaySeconds: 15
            periodSeconds: 5
