apiVersion: v1
kind: Secret
metadata:
  name: streamnxt-secrets
  namespace: streamnxt
type: Opaque
stringData:
  POSTGRES_DB: "ott_prod"
  POSTGRES_USER: "ott"
  POSTGRES_PASSWORD: "g3KRVn8dinTPnYeE"
  REDIS_PASSWORD: "2069433c03dab37f537746c"
  JWT_SECRET: "f96a985e54786a6e78b34635de6fcd39efc3c94be5a4d1f75ae8861b2cd5d6e4"
  JWT_REFRESH_SECRET: "39c82417b7f940eda2069433c03dab37f537746c491372e5f7466a961a5eb29d"
  JWT_EXPIRES_IN: "15m"
  JWT_REFRESH_EXPIRES_IN: "7d"
  ENCRYPTION_KEY: "cc2a7b9e9f00470ece2820e2fd8127501cf0f57846064532a892c6b13c748725"
  S3_REGION: "us-east-1"
  S3_BUCKET_CONTENT: "testdev26"
  S3_BUCKET_THUMBNAILS: "ott-thumbnails"
  S3_BUCKET_SUBTITLES: "ott-subtitles"
  S3_PUBLIC_URL: "https://minio.eliteworld.space"
  AD_SERVER_API_KEY: "a7f3e291b4c8d056e19f7a2b3c4d5e6f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d"
  AD_SERVER_URL: "https://ads.eliteworld.space"
  NEXT_PUBLIC_WS_URL: "wss://api.eliteworld.space"
  NEXT_PUBLIC_API_URL: "https://api.eliteworld.space"
  NEXT_PUBLIC_AD_SERVER_URL: "https://api.eliteworld.space"
  GRAFANA_ADMIN_USER: "admin"
  GRAFANA_ADMIN_PASSWORD: "admin"
  SERVICE_URL_WEB: "https://app.eliteworld.space"
  SERVICE_URL_ADMIN: "https://admin.eliteworld.space"
  SERVICE_URL_SUPER_ADMIN: "https://sadmin.eliteworld.space"
  SERVICE_URL_API: "https://api.eliteworld.space"
  SERVICE_URL_AD_SERVER: "https://ads.eliteworld.space"
  TMDB_API_KEY: ""
  TMDB_BASE_URL: "https://api.themoviedb.org/3"
  TMDB_IMAGE_BASE: "https://image.tmdb.org/t/p"
  TENANT_ID: "cmn7r3ebs00003kj42gxdosie"
  DEPLOYMENT_TIER: "starter"
  DEPLOYMENT_ID: ""
  LICENSE_ENFORCEMENT: "off"
  LICENSE_KEY: ""
  LICENSE_PATH: ""
  ENCRYPTION_KEY: "cc2a7b9e9f00470ece2820e2fd8127501cf0f57846064532a892c6b13c748725"